### ISSUE TITLE
handling  special characters

### ISSUE THREAD

**Issue by Zekke** [ReneNyffenegger/cpp-base64#5]
Hello, can you add an handling to special characters in the decode function ?
For example, with your actual implementation, "w6k=" will return "Ã©" instead of "é".

Thank you :)

**Comment by JomaCorpFX** [comment]
@Zekke "w6k=" decoded is equals to "é", The problem is on Windows, it uses UTF-16, you need to convert your std::string to std::wstring and print using Windows native function "https://docs.microsoft.com/en-us/windows/console/writeconsole"

Check my Answer in Stackoverflow, With detailed instructions.
https://stackoverflow.com/questions/2492077/output-unicode-strings-in-windows-console-app/54833872#54833872

**Comment by ReneNyffenegger** [comment]
Ã© is an é, encoded in UTF-8, but displayed as latin-1. If you process the Ã© in an "UTF-8 context", it will be displayed as é.
